---
# https://help.ubuntu.com/lts/serverguide/apparmor.html.en

- name: Ensure apparmor packages are present
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apparmor
    - apparmor-utils
    - apparmor-profiles
  register: pkg_result
  until: pkg_result is success

- name: Ensure apparmor profile is set
  template:
    src: apparmor-usr.bin.osqueryd.j2
    dest: /etc/apparmor.d/usr.bin.osqueryd
    mode: '0600'
    owner: root
    backup: yes
  notify:
    - reload osqueryd apparmor profile

- name: Apply apparmor profile for osquery
  command: aa-complain /usr/bin/osqueryd
#  command: aa-enforce /usr/bin/osqueryd
  register: aa_status
  changed_when: False
  failed_when: |
    aa_status.rc != 0 and
    "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?" not in aa_status.stderr

# Refine policy with `aa-logprof -f /var/log/syslog`
